# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EozDzibSvqOUqbgilzuZYYUEf5QSvXc7
"""

import streamlit as st
 
st.title("a")